version: "3.7"

services:
  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: casbin_rs
      POSTGRES_USER: casbin_rs
      POSTGRES_DB: casbin
